### PR TITLE
CI benchmarking

### PR DESCRIPTION
**Pull request by jeffa5**

### CODE REVIEW

**Comment by heidihoward** [comment]
throughput graph doesn't seem to have any data?

**Comment by jeffa5** [comment]
> throughput graph doesn't seem to have any data?

Think I've fixed that now, was due to a 0 rate causing `/ 0` error

**Comment by jeffa5** [comment]
@heidihoward should be ready to go now, including throughput data!

**Comment by heidihoward** [comment]
Can you put othervars somewhere else and just show the variable which changes in the legend? They are quite long, and they will likely on get longer 😜

**Comment by jeffa5** [comment]
> Can you put othervars somewhere else and just show the variable which changes in the legend? They are quite long, and they will likely on get longer 😜

Yes, worked out the variable ones and only made them on the legend, kept the invariant ones as a title

**Review by heidihoward — APPROVED** [review]
lgtm

**Pull request merged**
